/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

// import { LoopOnce } from "three/src/constants";
// https://github.com/mrdoob/three.js/blob/master/src/constants.js#L125
const LoopOnce = 2200;

export default function Model(props) {
  const { dark } = props;
  const light = dark ? 1 : 0;
  const seaRef = useRef();
  const cocoRef = useRef();
  const { nodes, materials, animations } = useGLTF("/3d/maldive-mini.gltf");
  const { actions } = useAnimations(animations, seaRef);
  const { actions: cocoActions } = useAnimations(animations, cocoRef);

  useEffect(() => {
    actions.SeaWave.play();
    cocoActions.Swing.setLoop(LoopOnce);
  }, []);
  return (
    <group {...props} dispose={null}>
      <group
        position={[3.571, 0.891, 1.47]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.5, 0.5, 0.5]}
      >
        <group position={[2.849, 0.313, -3.185]} scale={[0.169, 0.1, 0.1]}>
          <pointLight
            decay={2}
            color="#ff8b1c"
            intensity={light}
            rotation={[-Math.PI / 2, 0, 0]}
          />
        </group>
        <group position={[3.104, 0.309, -3.623]} scale={[0.169, 0.1, 0.1]}>
          <pointLight
            decay={2}
            color="#ff8b1c"
            intensity={light}
            rotation={[-Math.PI / 2, 0, 0]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002.geometry}
          material={nodes.Cube002.material}
          position={[-0.262, 0.851, -3.514]}
          rotation={[Math.PI, -1.562, Math.PI]}
          scale={[0.637, 1.03, 0.035]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004.geometry}
          material={nodes.Cube004.material}
          position={[0.103, 0.851, -3.547]}
          rotation={[Math.PI, -1.562, Math.PI]}
          scale={[0.383, 1.03, 0.035]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube006.geometry}
          material={nodes.Cube006.material}
          position={[-2.012, 0.127, -5.275]}
          rotation={[Math.PI, -1.57, Math.PI]}
          scale={[-0.05, -0.089, -1.436]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube007.geometry}
          material={nodes.Cube007.material}
          position={[3.685, 0.127, -3.906]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[-0.05, -0.089, -1.862]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube008.geometry}
          material={nodes.Cube008.material}
          position={[3.685, 0.127, -3.906]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[-0.05, -0.089, -1.862]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009.geometry}
          material={nodes.Cube009.material}
          position={[-2.012, 0.589, -5.275]}
          rotation={[Math.PI, -1.57, Math.PI]}
          scale={[-0.05, -0.089, -1.436]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube010.geometry}
          material={nodes.Cube010.material}
          position={[-1.68, 0.127, -5.275]}
          rotation={[Math.PI, -1.57, Math.PI]}
          scale={[-0.05, -0.089, -1.862]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube011.geometry}
          material={nodes.Cube011.material}
          position={[-1.68, 0.127, -5.275]}
          rotation={[Math.PI, -1.57, Math.PI]}
          scale={[-0.05, -0.089, -1.862]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube012.geometry}
          material={nodes.Cube012.material}
          position={[-1.68, 0.127, -5.275]}
          rotation={[Math.PI, -1.57, Math.PI]}
          scale={[-0.05, -0.089, -1.862]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube013.geometry}
          material={nodes.Cube013.material}
          position={[-1.68, 0.127, -5.275]}
          rotation={[Math.PI, -1.57, Math.PI]}
          scale={[-0.05, -0.089, -1.862]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube014.geometry}
          material={nodes.Cube014.material}
          position={[-1.68, 0.127, -5.275]}
          rotation={[Math.PI, -1.57, Math.PI]}
          scale={[-0.05, -0.089, -1.862]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015.geometry}
          material={nodes.Cube015.material}
          position={[-1.414, 0.141, -3.753]}
          rotation={[0, -0.777, 0]}
          scale={[0.517, 0.3, 0.647]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube016.geometry}
          material={nodes.Cube016.material}
          position={[-1.747, 0.358, -3.415]}
          rotation={[-0.945, -0.523, 2.537]}
          scale={[-0.517, -0.103, -0.241]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube017.geometry}
          material={nodes.Cube017.material}
          position={[-1.726, 0.388, -3.436]}
          rotation={[-0.945, -0.523, 2.537]}
          scale={[-0.517, -0.21, -0.241]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube018.geometry}
          material={nodes.Cube018.material}
          position={[-1.275, 0.209, -3.894]}
          rotation={[0, -0.777, -Math.PI]}
          scale={[-0.517, -0.21, -0.442]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube019.geometry}
          material={nodes.Cube019.material}
          position={[-1.797, 0.265, -3.364]}
          rotation={[0.989, -0.496, -2.515]}
          scale={[-0.517, -0.103, -0.101]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020.geometry}
          material={nodes.Cube020.material}
          position={[-2.311, 0.265, -4.014]}
          rotation={[0.989, -0.496, -2.515]}
          scale={[-0.517, -0.103, -0.101]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube021.geometry}
          material={nodes.Cube021.material}
          position={[-1.789, 0.209, -4.544]}
          rotation={[0, -0.777, -Math.PI]}
          scale={[-0.517, -0.21, -0.442]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube022.geometry}
          material={nodes.Cube022.material}
          position={[-2.239, 0.388, -4.086]}
          rotation={[-0.945, -0.523, 2.537]}
          scale={[-0.517, -0.21, -0.241]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube023.geometry}
          material={nodes.Cube023.material}
          position={[-2.26, 0.358, -4.065]}
          rotation={[-0.945, -0.523, 2.537]}
          scale={[-0.517, -0.103, -0.241]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube024.geometry}
          material={nodes.Cube024.material}
          position={[-1.928, 0.141, -4.403]}
          rotation={[0, -0.777, 0]}
          scale={[0.517, 0.3, 0.647]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube025.geometry}
          material={nodes.Cube025.material}
          position={[1.775, -0.515, -5.534]}
          scale={[1.95, 0.5, 1.3]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube026.geometry}
          material={nodes.Cube026.material}
          position={[3.685, 0.127, -3.906]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[-0.05, -0.089, -1.862]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube027.geometry}
          material={nodes.Cube027.material}
          position={[3.685, 0.127, -3.906]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[-0.05, -0.089, -1.862]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube028.geometry}
          material={nodes.Cube028.material}
          position={[3.685, 0.127, -3.906]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[-0.05, -0.089, -1.862]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube029.geometry}
          material={nodes.Cube029.material}
          position={[3.685, 0.127, -3.906]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[-0.05, -0.089, -1.862]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube030.geometry}
          material={nodes.Cube030.material}
          position={[3.685, 0.127, -3.906]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[-0.05, -0.089, -1.862]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube031.geometry}
          material={nodes.Cube031.material}
          position={[3.685, 0.127, -3.906]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[-0.05, -0.089, -1.862]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube033.geometry}
          material={nodes.Cube033.material}
          position={[1.775, -0.513, -6.608]}
          scale={[1.832, 0.436, 0.03]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube035.geometry}
          material={nodes.Cube035.material}
          position={[-0.114, 0.866, -0.158]}
          scale={[0.6, 0.643, 0.1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube036.geometry}
          material={nodes.Cube036.material}
          position={[-0.114, 0.866, -0.151]}
          scale={[0.02, 0.579, 0.03]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube037.geometry}
          material={nodes.Cube037.material}
          position={[0.166, 0.867, -0.15]}
          scale={[0.26, 0.579, 0.02]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder.geometry}
          material={nodes.Cylinder.material}
          position={[-1.61, 0.801, -4.16]}
          scale={[0.3, 1.418, 0.3]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001.geometry}
          material={nodes.Cylinder001.material}
          position={[-3.025, -1.401, -5.175]}
          scale={[0.99, 1.21, 0.99]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder002.geometry}
          material={nodes.Cylinder002.material}
          position={[-1.795, -1.196, -0.203]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder003.geometry}
          material={nodes.Cylinder003.material}
          position={[3.519, -1.196, -0.203]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder004.geometry}
          material={nodes.Cylinder004.material}
          position={[3.519, -1.243, -6.496]}
          scale={[0.99, 1.367, 0.99]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder005.geometry}
          material={nodes.Cylinder005.material}
          position={[0.069, -1.247, -6.496]}
          scale={[0.99, 1.369, 0.99]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder006.geometry}
          material={nodes.Cylinder006.material}
          position={[3.519, -1.243, -5.509]}
          scale={[0.99, 1.367, 0.99]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder007.geometry}
          material={nodes.Cylinder007.material}
          position={[0.069, -1.247, -5.509]}
          scale={[0.99, 1.369, 0.99]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder008.geometry}
          material={nodes.Cylinder008.material}
          position={[3.486, -1.243, -4.456]}
          scale={[0.99, 1.367, 0.99]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder009.geometry}
          material={nodes.Cylinder009.material}
          position={[0.037, -1.247, -4.456]}
          scale={[0.99, 1.369, 0.99]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder010.geometry}
          material={nodes.Cylinder010.material}
          position={[-0.285, -0.37, -6.657]}
          scale={[0.3, 0.227, 0.3]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder011.geometry}
          material={nodes.Cylinder011.material}
          position={[-0.482, -0.62, -7.077]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.161, 0.7, 0.161]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder012.geometry}
          material={nodes.Cylinder012.material}
          position={[-0.679, -0.37, -6.657]}
          scale={[0.3, 0.227, 0.3]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder013.geometry}
          material={nodes.Cylinder013.material}
          position={[-0.482, -0.82, -7.077]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.161, 0.7, 0.161]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder014.geometry}
          material={nodes.Cylinder014.material}
          position={[-0.482, -1.02, -7.077]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.161, 0.7, 0.161]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder015.geometry}
          material={nodes.Cylinder015.material}
          position={[-0.482, -1.22, -7.077]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.161, 0.7, 0.161]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder016.geometry}
          material={nodes.Cylinder016.material}
          position={[-0.482, -1.42, -7.077]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.161, 0.7, 0.161]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder017.geometry}
          material={nodes.Cylinder017.material}
          position={[-0.482, -0.42, -7.077]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.161, 0.7, 0.161]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder018.geometry}
          material={nodes.Cylinder018.material}
          position={[0.606, 0.293, -5.163]}
          scale={[0.3, 0.194, 0.239]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder019.geometry}
          material={nodes.Cylinder019.material}
          position={[0.408, 0.079, -5.498]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.128, 0.7, 0.138]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder020.geometry}
          material={nodes.Cylinder020.material}
          position={[0.212, 0.293, -5.163]}
          scale={[0.3, 0.194, 0.239]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder021.geometry}
          material={nodes.Cylinder021.material}
          position={[0.408, -0.092, -5.498]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.128, 0.7, 0.138]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder022.geometry}
          material={nodes.Cylinder022.material}
          position={[0.408, -0.263, -5.498]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.128, 0.7, 0.138]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder023.geometry}
          material={nodes.Cylinder023.material}
          position={[0.408, -0.435, -5.498]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.128, 0.7, 0.138]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder024.geometry}
          material={nodes.Cylinder024.material}
          position={[0.408, -0.606, -5.498]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.128, 0.7, 0.138]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder025.geometry}
          material={nodes.Cylinder025.material}
          position={[0.408, 0.25, -5.498]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.128, 0.7, 0.138]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DoorFrameBox.geometry}
          material={nodes.DoorFrameBox.material}
          position={[-0.067, 0.854, -3.48]}
          rotation={[Math.PI, -1.561, Math.PI]}
          scale={[0.85, 1.127, 1.083]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.GlassDoorBox1.geometry}
          material={nodes.GlassDoorBox1.material}
          position={[-0.428, 0.852, -3.524]}
          rotation={[Math.PI, -1.561, Math.PI]}
          scale={[0.078, 1.03, 0.268]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.GlassDoorBox2.geometry}
          material={nodes.GlassDoorBox2.material}
          position={[-0.079, 0.852, -3.521]}
          rotation={[Math.PI, -1.561, Math.PI]}
          scale={[0.078, 1.03, 0.296]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HutMainFloor001.geometry}
          material={nodes.HutMainFloor001.material}
          position={[0.23, -0.098, -2.656]}
          scale={[3.5, 0.1, 2.666]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LightBall1.geometry}
          material={nodes.LightBall1.material}
          position={[3.104, 0.306, -3.619]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LightBall2.geometry}
          material={nodes.LightBall2.material}
          position={[2.849, 0.306, -3.196]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Parasol.geometry}
          material={nodes.Parasol.material}
          position={[-1.61, 1.366, -4.16]}
          scale={[0.8, 0.177, 0.8]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.PoolWater.geometry}
          material={materials.PoolWater}
          position={[1.773, -0.84, -5.825]}
          scale={[1.831, 0.99, 0.76]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SideWindowBox1.geometry}
          material={nodes.SideWindowBox1.material}
          position={[-1.301, 0.916, -3.058]}
          rotation={[0, -0.8, 0]}
          scale={[0.4, 1.216, 1.126]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SideWindowBox2.geometry}
          material={nodes.SideWindowBox2.material}
          position={[1.128, 0.912, -3.034]}
          rotation={[Math.PI, -0.776, Math.PI]}
          scale={[0.4, 1.216, 1.126]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SideWindowGlass1.geometry}
          material={nodes.SideWindowGlass1.material}
          position={[-1.301, 0.916, -3.058]}
          rotation={[0, -0.794, 0]}
          scale={[0.078, 1.113, 1.048]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SideWindowGlass2.geometry}
          material={nodes.SideWindowGlass2.material}
          position={[1.128, 0.912, -3.034]}
          rotation={[Math.PI, -0.776, Math.PI]}
          scale={[0.078, 1.113, 1.048]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SlidingFrontGlassDoor.geometry}
          material={nodes.SlidingFrontGlassDoor.material}
          position={[-0.394, 0.867, -0.201]}
          scale={[0.26, 0.579, 0.02]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SlidingGlassDoorBox.geometry}
          material={nodes.SlidingGlassDoorBox.material}
          position={[0.258, 0.852, -3.473]}
          rotation={[Math.PI, -1.561, Math.PI]}
          scale={[0.078, 1.03, 0.332]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stairs.geometry}
          material={nodes.Stairs.material}
          position={[-0.488, -0.093, -5.423]}
          scale={[0.3, 0.1, 0.1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stairs001.geometry}
          material={nodes.Stairs001.material}
          position={[-0.117, -0.152, 0.149]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[0.597, 0.156, 0.148]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cone.geometry}
          material={materials["Roof.001"]}
          position={[-0.099, 3.02, -1.834]}
          rotation={[0, -1.179, 0]}
          scale={[1.477, 1.436, 1.477]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube.geometry}
          material={nodes.Cube.material}
          position={[-2.577, 0.824, -3.714]}
          rotation={[0, -1.182, 0]}
          scale={[1.9, 2.58, 0.05]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001.geometry}
          material={nodes.Cube001.material}
          position={[-1.942, 0.822, -1.059]}
          scale={[0.05, 2.573, 1.404]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003.geometry}
          material={nodes.Cube003.material}
          position={[3.689, 0.822, -1.188]}
          scale={[0.05, 2.573, 1.579]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005.geometry}
          material={nodes.Cube005.material}
          position={[2.714, 0.822, -2.427]}
          scale={[1.134, 2.573, 0.07]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.FloorBox.geometry}
          material={nodes.FloorBox.material}
          position={[-0.099, 0.162, -1.834]}
          rotation={[Math.PI, -1.169, Math.PI]}
          scale={[1.783, 0.061, 1.783]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HutBodyCylinder.geometry}
          material={nodes.HutBodyCylinder.material}
          position={[-0.099, 0.906, -1.834]}
          rotation={[Math.PI, -1.169, Math.PI]}
          scale={[1.926, 0.684, 1.926]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HutMainFloor.geometry}
          material={nodes.HutMainFloor.material}
          position={[0.23, 0.052, -2.656]}
          scale={[3.5, 0.05, 2.666]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BeachBase.geometry}
        material={nodes.BeachBase.material}
        position={[0, -0.028, 0]}
        scale={[1.076, 1.01, 1.076]}
      />
      <mesh
        castShadow
        receiveShadow
        ref={seaRef}
        geometry={nodes.SeaWater.geometry}
        material={materials.WaterMat}
        position={[3.198, -0.093, 0]}
        scale={[4, 4, 4]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.UnderwaterBase.geometry}
        material={nodes.UnderwaterBase.material}
        position={[5.643, -0.544, 0]}
        scale={[1.76, 0.9, 4.28]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stone4.geometry}
        material={nodes.Stone4.material}
        position={[-2.184, 1.108, -3.271]}
        rotation={[0.068, 0.543, -0.13]}
        scale={[0.571, 0.273, 0.795]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stone7.geometry}
        material={nodes.Stone7.material}
        position={[5.506, -0.38, -3.328]}
        rotation={[0, -1.181, 0]}
        scale={[0.571, 0.273, 0.795]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stone5.geometry}
        material={nodes.Stone5.material}
        position={[5.086, -0.379, 3.526]}
        rotation={[-3.056, -1.035, -2.916]}
        scale={[0.349, 0.273, 0.486]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stone1.geometry}
        material={nodes.Stone1.material}
        position={[-3.273, 1.176, 2.667]}
        rotation={[0.731, -1.542, 0.902]}
        scale={[0.441, 0.459, 0.541]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stone3.geometry}
        material={nodes.Stone3.material}
        position={[-3.271, 1.147, 1.873]}
        rotation={[0.066, -1.28, 0.235]}
        scale={[0.288, 0.313, 0.348]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stone2.geometry}
        material={nodes.Stone2.material}
        position={[-2.679, 1.147, 3.225]}
        rotation={[0.019, 0.174, 0.168]}
        scale={[0.411, 0.447, 0.498]}
      />
      <mesh
        castShadow
        receiveShadow
        ref={cocoRef}
        onClick={() => {
          cocoActions.Swing.reset();
          cocoActions.Swing.play();
        }}
        geometry={nodes.CoconutTree.geometry}
        material={materials.CoconutTree}
        position={[-3.039, 0.858, -3.14]}
        scale={[0.182, 0.182, 0.182]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane_1.geometry}
          material={nodes.Plane_1.material}
          position={[2.615, 16.604, -2.547]}
          rotation={[-0.089, -0.104, -0.229]}
          scale={[4.662, 4.662, 1.838]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001.geometry}
          material={nodes.Plane001.material}
          position={[1.558, 16.319, -4.85]}
          rotation={[-0.079, 1.144, -0.337]}
          scale={[4.17, 4.17, 1.644]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002_1.geometry}
          material={nodes.Plane002_1.material}
          position={[-1.107, 16.925, -4.282]}
          rotation={[-2.742, 0.649, 2.816]}
          scale={[4.379, 4.379, 1.726]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane003_1.geometry}
          material={nodes.Plane003_1.material}
          position={[-1.514, 16.604, -1.703]}
          rotation={[-3.036, -0.497, 2.995]}
          scale={[4.518, 4.518, 1.781]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004_1.geometry}
          material={nodes.Plane004_1.material}
          position={[0.502, 16.604, -1.234]}
          rotation={[0.164, -1.187, 0.252]}
          scale={[4.774, 4.774, 1.882]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane005.geometry}
          material={nodes.Plane005.material}
          position={[0.067, 17.29, -4.282]}
          rotation={[2.415, 1.371, -2.255]}
          scale={[2.605, 2.605, 1.027]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane006.geometry}
          material={nodes.Plane006.material}
          position={[1.638, 17.29, -3.381]}
          rotation={[0.056, 0.455, -0.13]}
          scale={[2.302, 2.302, 0.908]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane007.geometry}
          material={nodes.Plane007.material}
          position={[1.638, 17.014, -1.831]}
          rotation={[0.059, -0.535, -0.075]}
          scale={[2.302, 2.302, 0.908]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane008.geometry}
          material={nodes.Plane008.material}
          position={[0.236, 17.23, -1.653]}
          rotation={[-2.908, -1.151, -2.891]}
          scale={[2.302, 2.302, 0.908]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane009.geometry}
          material={nodes.Plane009.material}
          position={[-0.655, 17.29, -3.049]}
          rotation={[2.689, 0.016, -2.923]}
          scale={[2.208, 2.208, 0.87]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane010.geometry}
          material={nodes.Plane010.material}
          position={[2.615, 16.604, -2.547]}
          rotation={[-0.089, -0.104, -0.229]}
          scale={[4.662, 4.662, 1.838]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane011.geometry}
          material={nodes.Plane011.material}
          position={[1.558, 16.319, -4.85]}
          rotation={[-0.079, 1.144, -0.337]}
          scale={[4.17, 4.17, 1.644]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane012.geometry}
          material={nodes.Plane012.material}
          position={[-1.107, 16.925, -4.282]}
          rotation={[-2.742, 0.649, 2.816]}
          scale={[4.379, 4.379, 1.726]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane013.geometry}
          material={nodes.Plane013.material}
          position={[-1.514, 16.604, -1.703]}
          rotation={[-3.036, -0.497, 2.995]}
          scale={[4.518, 4.518, 1.781]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014.geometry}
          material={nodes.Plane014.material}
          position={[0.502, 16.604, -1.234]}
          rotation={[0.164, -1.187, 0.252]}
          scale={[4.774, 4.774, 1.882]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane015.geometry}
          material={nodes.Plane015.material}
          position={[0.067, 17.29, -4.282]}
          rotation={[2.415, 1.371, -2.255]}
          scale={[2.605, 2.605, 1.027]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane016.geometry}
          material={nodes.Plane016.material}
          position={[1.638, 17.29, -3.381]}
          rotation={[0.056, 0.455, -0.13]}
          scale={[2.302, 2.302, 0.908]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane017.geometry}
          material={nodes.Plane017.material}
          position={[1.638, 17.014, -1.831]}
          rotation={[0.059, -0.535, -0.075]}
          scale={[2.302, 2.302, 0.908]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane018.geometry}
          material={nodes.Plane018.material}
          position={[0.236, 17.23, -1.653]}
          rotation={[-2.908, -1.151, -2.891]}
          scale={[2.302, 2.302, 0.908]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane019.geometry}
          material={nodes.Plane019.material}
          position={[-0.655, 17.29, -3.049]}
          rotation={[2.689, 0.016, -2.923]}
          scale={[2.208, 2.208, 0.87]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stone1001.geometry}
        material={nodes.Stone1001.material}
        position={[-3.273, 1.242, -3.813]}
        rotation={[0.731, -1.542, 0.902]}
        scale={[0.441, 0.459, 0.541]}
      />
    </group>
  );
}

useGLTF.preload("/3d/maldive-mini.gltf");
