/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

const DOOR_OPEN = -0.87;

export default function Model(props) {
  const group = useRef();
  const doorRef = useRef();
  const [doorOpen, setDoorOpen] = useState(true);
  const { nodes } = useGLTF("/3d/home.gltf");

  useFrame(() => {
    const y = doorRef.current.rotation.y;
    let addition = y < 0 ? 0.01 : 0;
    if (doorOpen) {
      addition = y > DOOR_OPEN ? -0.01 : 0;
    }
    if (addition) {
      doorRef.current.rotation.y += addition;
    }
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-1.89, 0, 1.33]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_4.geometry}
          material={nodes.Cylinder_4.material}
          position={[0, 1.39, 0]}
          scale={[0.54, 1.31, 0.48]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_5.geometry}
          material={nodes.Cylinder_5.material}
          position={[0, 0.92, 0]}
          scale={[0.09, 1.88, 0.07]}
        />
      </group>
      <group position={[-1.29, 0, 0.23]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_6.geometry}
          material={nodes.Cylinder_6.material}
          position={[-1.13, 0.25, -2.33]}
          scale={[0.32, 0.54, 0.32]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_7.geometry}
          material={nodes.Cylinder_7.material}
          position={[-1.13, 0.25, -0.29]}
          scale={[0.32, 0.52, 0.32]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_8.geometry}
          material={nodes.Cylinder_8.material}
          position={[1.12, 0.25, -2.33]}
          scale={[0.32, 0.5, 0.32]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_9.geometry}
          material={nodes.Cylinder_9.material}
          position={[1.12, 0.25, -0.29]}
          scale={[0.32, 0.52, 0.32]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Box_10.geometry}
          material={nodes.Box_10.material}
          position={[0, 0.67, -1.32]}
          scale={[2.88, 0.76, 2.67]}
        />
      </group>
      <group position={[3.51, 0.88, -1.27]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Box_11.geometry}
          material={nodes.Box_11.material}
          position={[0.01, -0.07, 0]}
          rotation={[0, 0, -0.11]}
          scale={[0.01, 0.58, 0.83]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Box_12.geometry}
          material={nodes.Box_12.material}
          position={[-0.26, -0.37, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.49, 0.02, 0.83]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Box_13.geometry}
          material={nodes.Box_13.material}
          position={[0, -0.6, 0]}
          scale={[0.99, 0.47, 1.93]}
        />
      </group>
      <group position={[-2.17, 0, -6.29]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_11.geometry}
          material={nodes.Cylinder_11.material}
          position={[0, 0.92, 0]}
          scale={[0.09, 1.88, 0.07]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_10.geometry}
          material={nodes.Cylinder_10.material}
          position={[0, 1.39, 0]}
          scale={[0.54, 1.31, 0.48]}
        />
      </group>
      <group position={[-1.87, 0, 3.82]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_12.geometry}
          material={nodes.Cylinder_12.material}
          position={[-0.69, 1.06, 0]}
          rotation={[0, 0, -1.32]}
          scale={[0.68, 0.12, 0.55]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_13.geometry}
          material={nodes.Cylinder_13.material}
          position={[0, 0.34, 0]}
          scale={[0.61, 0.54, 0.6]}
        />
      </group>
      <group position={[0, 0, -8.15]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Box_14.geometry}
          material={nodes.Box_14.material}
          position={[0.6, -0.03, 0]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[-5.29, 0.1, 1.52]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Box_15.geometry}
          material={nodes.Box_15.material}
          position={[0.59, 0, 1]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[-6.89, 0.1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Box_16.geometry}
          material={nodes.Box_16.material}
          position={[0.59, 0, -1]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[-6.89, 0.1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Box_17.geometry}
          material={nodes.Box_17.material}
          position={[-2.46, 0, 0]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[-0.8, 0.1, 1.52]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Box_18.geometry}
          material={nodes.Box_18.material}
          position={[3.63, 0, 0]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[-0.8, 0.1, 1.52]}
        />
      </group>
      <group ref={doorRef} position={[3.24, 0, -5.2]} rotation={[0, -0.87, 0]}>
        <mesh
          onClick={() => setDoorOpen(!doorOpen)}
          castShadow
          receiveShadow
          geometry={nodes.Box_19.geometry}
          material={nodes.Box_19.material}
          position={[-0.61, 1.4, 0]}
          scale={[-1.26, 2.7, 0.07]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box.geometry}
        material={nodes.Box.material}
        position={[0.59, 0, -0.89]}
        scale={[6.89, 0.1, 12]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box_1.geometry}
        material={nodes.Box_1.material}
        position={[-2.84, 1.46, -2.15]}
        scale={[0.05, 2.81, 14.51]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box_2.geometry}
        material={nodes.Box_2.material}
        position={[-0.11, 1.4, 2.42]}
        scale={[5.42, 2.7, 0.07]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box_4.geometry}
        material={nodes.Box_4.material}
        position={[0.63, 1.4, 4.93]}
        scale={[0.16, 2.7, 0.37]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box_5.geometry}
        material={nodes.Box_5.material}
        position={[0.63, 1.4, 2.65]}
        scale={[0.16, 2.7, 0.37]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box_7.geometry}
        material={nodes.Box_7.material}
        position={[-2, 1.4, -5.2]}
        scale={[1.63, 2.7, 0.07]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box_8.geometry}
        material={nodes.Box_8.material}
        position={[3.64, 1.4, -5.2]}
        scale={[0.79, 2.7, 0.07]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box_6.geometry}
        material={nodes.Box_6.material}
        position={[0.63, 1.4, 3.79]}
        scale={[0.16, 2.7, 1.9]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box_9.geometry}
        material={nodes.Box_9.material}
        position={[0.4, 1.4, -5.2]}
        scale={[3.19, 2.7, 0.07]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere.geometry}
        material={nodes.Sphere.material}
        position={[-0.72, 1.01, 2.23]}
        rotation={[0.15, Math.PI / 2, 0]}
        scale={[0.08, 1, 0.3]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={nodes.Cylinder.material}
        position={[-1.21, 0.19, -6.36]}
        scale={[0.41, 0.28, 0.39]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder_1.geometry}
        material={nodes.Cylinder_1.material}
        position={[-2.12, 1.11, -3.66]}
        scale={[0.49, 0.23, 0.49]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder_2.geometry}
        material={nodes.Cylinder_2.material}
        position={[-2.13, 0.77, -3.66]}
        scale={[0.06, 0.47, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box_3.geometry}
        material={nodes.Box_3.material}
        position={[-2, 0.29, -3.68]}
        scale={[1.2, 0.5, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder_3.geometry}
        material={nodes.Cylinder_3.material}
        position={[2.54, 0.19, -1.25]}
        scale={[0.28, 0.29, 0.3]}
      />
    </group>
  );
}

useGLTF.preload("/3d/home.gltf");
